### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by snegurova** [snegurova/homepage#12]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by innasn** [comment]
👶 10th August 1984 - life
Born in Kryvyy Rih, Ukraine

🎓 1st September 1997 – 20th June 2001 - education
Student at Central city liceum, physics-maths class
- honoured a  gold medal
- took 2nd place at the State Dnipro Olympiad in Math
- Every year first in the city in Math

🎓 1st September 2011 – 15th June 2006 - education
Student at Economic Faculty at Kryvyy Rih National University

- took 2nd place at the university Olympiad in English
- took 3nd place as a part of the university team in Ukrainian tennis competitions
- got Master's Degree with honors
- after for years got my first job in the bank

🏦 June, 2005 - June 2015 PAT "Ukrsocbank" - work
As a Head of the branch had been working in bank, since April, 2009

- achievement sales goals with a team;
- mentoring and onboarding new members with CRM and internal financial applications.

👶 27th July 2007 - life
My daughter was born

🖥️ December 2016 - Present  - work
Web-agency vivwebsolutions.com (USA) — Project Manager

🖥️ April 2017 - December 2018 - work
Web-agency artvolkov.ru, Russia — Project Manager

🖥️ August 2018 - Present - work
Web-agency clicktie.com, Canada — Project Manager

- creating site concept
- setting technical tasks
- site prototyping
- choosing developers, designers for the project or for hiring
- quality assurance

🎓 1st September 2020 – Present - education
Student at RS School
Pet projects:
https://rolling-scopes-school.github.io/snegurova-JS2020Q3/calculator/
https://rolling-scopes-school.github.io/snegurova-JS2020Q3/shelter/pages/main/
https://rolling-scopes-school.github.io/snegurova-JS2020Q3/momentum/
https://rolling-scopes-school.github.io/snegurova-JS2020Q3/virtual-keyboard/
https://rolling-scopes-school.github.io/snegurova-JS2020Q3/gem-puzzle/
https://rolling-scopes-school.github.io/snegurova-JS2020Q3/covid-dashboard/
